version: '3.3'

# Define services
services:

  # App backend service
  api:
    # Configuration for building the docker image for the backend service
    container_name: project_api
    build:
      context: api/Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Forward the exposed port 8000 on the container to port 8000 on the host machine
    restart: always
    depends_on: 
      - database # Starts mysql db first
    networks:
      -frontend
      - backend

  # App frontemd service
  webclient:
    container_name: project_webclient
    build:
      context: webclient/Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000"
    restart: always
    depends_on: 
      - database
      - api
    networks:
      - frontend

  # Database Service
  database:
    container_name: project_database
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    build:
      context: database/Dockerfile
      dockerfile: Dockerfile
    networks:
      - backend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: