version: '3.3'

# Define services
services:

  # App backend service
  api:
    # Configuration for building the docker image for the backend service
    container_name: project-api
    build:
      context: api # Either a path to a directory containing a Dockerfile, or a url to a git repository
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8000 on the container to port 8000 on the host machine
    restart: always
    depends_on: 
      - database # Starts mysql db first
    networks:
      - backend
    tty: true

  # App frontend service
  webclient:
    container_name: project-webclient
    build:
      context: webclient
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on: 
      - database
      - api
    networks:
      - backend
    tty: true

  # Database Service
  database:
    environment: 
      MYSQL_DATABASE: project_db
      MYSQL_ROOT_PASSWORD: password
    container_name: project-database
    ports:
      - "3306:3306"
    restart: always
    build:
      context: database
      dockerfile: Dockerfile
    networks:
      - backend
    tty: true

# Networks to be created to facilitate communication between containers
networks:
  backend: